import Link from "next/link";
import { cookies, headers } from "next/headers";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { ArrowLeft, Mail, Pencil, ShieldCheck, Trash2 } from "lucide-react";
import { AdminNotice } from "../../../../components/AdminNotice";
import { ConfirmSubmitButton } from "../../../../components/ConfirmSubmitButton";
import { cookieName, getAdminSession } from "../../../../lib/admin-auth";
import { createAdminPasswordLink, deleteAdminAccount, findAdminAccountById, updateAdminAccount } from "../../../../lib/admin-users";
import { actorFromAdminSession, recordAuditEvent } from "../../../../lib/audit-log";

export const dynamic = "force-dynamic";

export default async function UciUserDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ notice?: string }> }) {
  const session = await requireSuperAdmin();
  const { id } = await params;
  const query = await searchParams;
  const account = await findAdminAccountById(id);
  if (!account || account.role !== "uci") return <div className="admin-page"><div className="wide"><section className="admin-panel"><h1>ไม่พบผู้ใช้ UCI</h1><Link className="secondary" href="/admin/uci"><ArrowLeft/>กลับรายการ</Link></section></div></div>;
  return <div className="admin-page admin-detail-page"><div className="wide"><div className="admin-topline"><div><span className="eyebrow">UCI User</span><h1>ข้อมูลผู้ใช้ UCI</h1><p>แก้ไขข้อมูล ปิดใช้งาน ส่งลิงก์ตั้งรหัสผ่าน หรือลบบัญชี</p><small className="admin-role-badge"><ShieldCheck/>Super Admin • {session.email}</small></div><Link className="secondary" href="/admin/uci"><ArrowLeft/>กลับรายการ UCI</Link></div><AdminNotice code={query.notice}/><article className="admin-panel"><section className="admin-detail-block"><dl className="admin-detail-list"><div><dt>อีเมล</dt><dd>{account.email}</dd></div><div><dt>ชื่อ</dt><dd>{account.name || "-"}</dd></div><div><dt>เบอร์ติดต่อ</dt><dd>{account.phone || "-"}</dd></div><div><dt>สถานะ</dt><dd>{account.disabled ? "ปิดใช้งาน" : "ใช้งานได้"}</dd></div><div><dt>รหัสผ่าน</dt><dd>{account.passwordHash ? "ตั้งรหัสผ่านแล้ว" : "รอตั้งรหัสผ่าน"}</dd></div></dl></section><section className="admin-detail-block"><h3>แก้ไขข้อมูล</h3><form action={updateUciAction} className="admin-form"><input type="hidden" name="id" value={account.id}/><div className="form-grid compact-grid"><label>ชื่อ<input name="name" defaultValue={account.name} required/></label><label>อีเมล<input type="email" name="email" defaultValue={account.email} required/></label><label>เบอร์ติดต่อ<input name="phone" defaultValue={account.phone}/></label><label className="inline-check"><input type="checkbox" name="disabled" defaultChecked={account.disabled}/> ปิดใช้งาน</label></div><button className="primary" type="submit"><Pencil/>บันทึกข้อมูล</button></form></section><section className="admin-detail-block"><h3>การจัดการบัญชี</h3><div className="admin-detail-actions"><form action={resendPasswordAction}><input type="hidden" name="id" value={account.id}/><button className="secondary" type="submit"><Mail/>ส่งลิงก์ตั้งรหัสผ่านใหม่</button></form><form action={deleteUciAction}><input type="hidden" name="id" value={account.id}/><ConfirmSubmitButton className="danger-btn" type="submit" message="ยืนยันลบผู้ใช้ UCI นี้?"><Trash2/>ลบผู้ใช้ UCI</ConfirmSubmitButton></form></div></section></article></div></div>;
}

async function updateUciAction(formData: FormData) { "use server"; const session = await requireSuperAdmin(); const id = text(formData, "id"); const account = await updateAdminAccount(id, { name: text(formData, "name"), email: text(formData, "email"), phone: text(formData, "phone"), disabled: formData.get("disabled") === "on" }); if (account.role !== "uci") throw new Error("บัญชีนี้ไม่ใช่ผู้ใช้ UCI"); await recordAuditEvent({ actor: actorFromAdminSession(session), action: "uci_user.updated", entityType: "uci_user", entityId: id, summary: `แก้ไขผู้ใช้ UCI ${account.email}` }, await headers()); revalidatePath("/admin/uci"); revalidatePath(`/admin/uci/${encodeURIComponent(id)}`); revalidatePath("/uci"); redirect(`/admin/uci/${encodeURIComponent(id)}?notice=member_saved`); }
async function resendPasswordAction(formData: FormData) { "use server"; const session = await requireSuperAdmin(); const result = await createAdminPasswordLink(text(formData, "id")); if (result.account.role !== "uci") throw new Error("บัญชีนี้ไม่ใช่ผู้ใช้ UCI"); await recordAuditEvent({ actor: actorFromAdminSession(session), action: "uci_user.password_link_sent", entityType: "uci_user", entityId: result.account.id, summary: `ส่งลิงก์ตั้งรหัสผ่านให้ ${result.account.email}` }, await headers()); revalidatePath(`/admin/uci/${encodeURIComponent(result.account.id)}`); redirect(`/admin/uci/${encodeURIComponent(result.account.id)}?notice=password_link_sent`); }
async function deleteUciAction(formData: FormData) { "use server"; const session = await requireSuperAdmin(); const id = text(formData, "id"); const account = await findAdminAccountById(id); if (!account || account.role !== "uci") throw new Error("ไม่พบผู้ใช้ UCI"); await deleteAdminAccount(id); await recordAuditEvent({ actor: actorFromAdminSession(session), action: "uci_user.deleted", entityType: "uci_user", entityId: id, summary: "ลบผู้ใช้ UCI" }, await headers()); revalidatePath("/admin/uci"); revalidatePath("/uci"); redirect("/admin/uci?notice=member_deleted"); }
async function requireSuperAdmin() { const session = getAdminSession((await cookies()).get(cookieName)?.value); if (!session || session.role !== "super_admin") redirect("/admin"); return session; }
function text(formData: FormData, name: string) { return String(formData.get(name) ?? "").replace(/\s+/g, " ").trim(); }
