import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, Download, Handshake, Lightbulb, MapPin, Scale, ShieldCheck, Trophy, Users } from "lucide-react";

const criteria=["ความเป็นนวัตกรรม","ความเป็นไปได้และการนำไปใช้","ผลกระทบต่อประชาชนและองค์กร","ความคุ้มค่าและการขยายผล"];
const faq=["ผู้สมัครเข้าร่วมการประกวดนวัตกรรมต้องเป็นข้าราชการตำรวจหรือไม่","สามารถส่งผลงานเข้าประกวดได้มากกว่า 1 ผลงานหรือไม่","ระยะเวลาการส่งผลงานคือช่วงใด","ผลงานที่เคยส่งประกวดเวทีอื่นสามารถส่งได้หรือไม่","นวัตกรรมต้องเป็นเทคโนโลยีขั้นสูงเท่านั้นหรือไม่"];
export default function Home(){return <>
  <section className="home-hero"><div className="hero-media"/><div className="wide hero-content"><div className="hero-values left"><span><ShieldCheck/>SECURITY<small>ความปลอดภัย</small></span><span><Scale/>JUSTICE<small>ความยุติธรรม</small></span><span><Users/>SERVICE<small>บริการประชาชน</small></span></div><div className="hero-center"><span className="crest"><ShieldCheck/></span><h1>Police Innovation Contest <b>2026</b></h1><p>การประกวดนวัตกรรม สำนักงานตำรวจแห่งชาติ<br/>ประจำปี พ.ศ. 2569</p><div><Link className="primary" href="/register">ลงทะเบียนเข้าร่วมงาน</Link><Link className="secondary" href="/submit">สมัครประกวดนวัตกรรม</Link></div></div><div className="hero-values right"><span><Lightbulb/>INNOVATION<small>นวัตกรรม</small></span><span><Handshake/>COLLABORATION<small>ความร่วมมือ</small></span><span><CheckCircle2/>EFFICIENCY<small>ประสิทธิภาพ</small></span></div></div></section>
  <section className="band" id="project"><div className="wide"><span className="eyebrow">Registration</span><h2>เลือกประเภทการลงทะเบียน</h2><div className="choice-grid"><article><Users/><span>Event Attendee</span><h3>ลงทะเบียนเข้าร่วมงาน</h3><p>สำหรับผู้เข้าร่วมงาน ผู้ติดตาม และผู้ที่ต้องการรับ QR Code สำหรับเช็คอิน</p><Link className="primary" href="/register">ลงทะเบียนเข้าร่วมงาน</Link></article><article><Lightbulb/><span>Innovation Submission</span><h3>สมัครประกวดนวัตกรรม</h3><p>กรอกข้อมูลผู้สมัคร รายละเอียดผลงาน และแนบเอกสารประกอบการพิจารณา</p><Link className="secondary" href="/submit">สมัครประกวดนวัตกรรม</Link></article></div></div></section>
  <section className="project-section"><div className="wide"><span className="eyebrow">Contest Details</span><h2>รายละเอียดข้อมูลการประกวดนวัตกรรม</h2><div className="three-grid"><article><h3>รายละเอียดวัตถุประสงค์การประกวด</h3><p>เปิดพื้นที่ให้ข้าราชการตำรวจนำเสนอแนวคิด ผลงาน และนวัตกรรมที่ช่วยเพิ่มประสิทธิภาพการปฏิบัติงาน ยกระดับการบริการประชาชน และสร้างความปลอดภัยอย่างยั่งยืน</p></article><article><h3>นิยามนวัตกรรม</h3><p>แนวคิด กระบวนการ เครื่องมือ หรือเทคโนโลยีที่สร้างคุณค่าใหม่ สามารถนำไปใช้จริง และแก้ปัญหาได้อย่างมีประสิทธิผล</p></article><article><h3>นวัตกรรมตำรวจ</h3><p>นวัตกรรมที่สนับสนุนภารกิจป้องกันปราบปราม อำนวยความยุติธรรม บริการประชาชน หรือพัฒนาการบริหารจัดการองค์กร</p></article></div>
  <div className="detail-grid" id="awards"><article><span className="eyebrow">เกณฑ์การพิจารณา</span><h3>เกณฑ์การตัดสินและคัดกรอง</h3>{criteria.map((item,i)=><p className="score" key={item}><span>{item}</span><b>{[25,25,30,20][i]} คะแนน</b></p>)}</article><article><Trophy/><span className="eyebrow">Awards</span><h3>เงินรางวัลและโล่เกียรติยศ</h3><div className="award-grid"><b>ชนะเลิศ</b><b>รองชนะเลิศ</b><b>รางวัลชมเชย</b></div></article></div>
  <div className="downloads" id="downloads"><div><span className="eyebrow">Downloads</span><h3>เอกสารและแบบฟอร์มประกวดนวัตกรรม</h3></div><a href="/documents/project-details.txt" download><Download/>ดาวน์โหลดรายละเอียดโครงการ</a><a href="/documents/submission-checklist.txt" download><Download/>ดาวน์โหลดรายการเอกสารส่งผลงาน</a></div>
  <div className="schedule" id="schedule"><CalendarDays/><div><span className="eyebrow">Schedule</span><h2>กำหนดการประกวด</h2><ol><li><b>20 กรกฎาคม 2569</b><span>เปิดรับสมัครผลงานนวัตกรรม</span></li><li><b>13 สิงหาคม 2569</b><span>ประกาศรายชื่อผลงานผ่านรอบคัดเลือก</span></li><li><b>24 สิงหาคม 2569</b><span>นำเสนอผลงานและประกาศผล</span></li></ol></div></div>
  <div className="faq" id="faq"><span className="eyebrow">คำถามที่พบบ่อย FAQ</span>{faq.map(q=><details key={q}><summary>{q}<ArrowRight/></summary><p>โปรดตรวจสอบประกาศและหลักเกณฑ์ฉบับเต็ม หรือติดต่อทีมงานโครงการเพื่อยืนยันข้อมูลล่าสุด</p></details>)}</div>
  <div className="location"><MapPin/><div><h3>แผนที่การเดินทาง</h3><p>สำนักงานตำรวจแห่งชาติ ถนนพระรามที่ 1 แขวงปทุมวัน กรุงเทพมหานคร 10330</p><a className="secondary" href="https://www.google.com/maps/search/?api=1&query=สำนักงานตำรวจแห่งชาติ+ถนนพระรามที่+1" target="_blank" rel="noreferrer">เปิดใน Google Maps</a></div></div>
  </div></section>
  </>}
