"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { FileText, Plus, Trash2 } from "lucide-react";
const docs=[['ownership','3.1 หลักฐานความเป็นเจ้าของผลงาน'],['concept','3.2 แบบสรุปผลงานโดยย่อ'],['prototype','3.3 หลักฐานต้นแบบหรือการทดลอง'],['implementation','3.4 แผนต่อยอดใช้งานจริง']] as const;
type TeamMember={title:string;firstName:string;lastName:string;citizenId:string;phone:string;email:string;division:string;bureau:string};
const emptyMember=():TeamMember=>({title:'',firstName:'',lastName:'',citizenId:'',phone:'',email:'',division:'',bureau:''});
export function SubmissionForm(){const router=useRouter();const [type,setType]=useState<'individual'|'team'>('individual'),[members,setMembers]=useState<TeamMember[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);function updateMember(index:number,key:keyof TeamMember,value:string){setMembers(current=>current.map((member,i)=>i===index?{...member,[key]:value}:member))}async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);form.set('submissionType',type);form.set('teamMembers',JSON.stringify(type==='team'?members:[]));const response=await fetch('/api/submissions',{method:'POST',body:form});const data=await response.json();if(response.ok)router.push(`/submit/success?code=${data.submissionCode}`);else{setError(data.error);setBusy(false)}}return <form className="form-card submission" onSubmit={submit}><div className="form-heading"><span>แบบฟอร์มส่งผลงาน</span><h2>ข้อมูลใบสมัครประกวด</h2><p>บัญชีที่ใช้ลงทะเบียนและส่งผลงานต้องเป็นอีเมลเดียวกัน</p></div>
<section className="form-section"><header><span>Applicant</span><h3>1. ข้อมูลผู้สมัคร</h3></header><div className="type-picker"><button type="button" className={type==='individual'?'active':''} onClick={()=>setType('individual')}>ส่งเดี่ยว<small>ส่งในนามบุคคล</small></button><button type="button" className={type==='team'?'active':''} onClick={()=>setType('team')}>ส่งแบบกลุ่ม<small>ระบุชื่อทีมและสมาชิก</small></button></div>{type==='team'&&<label>ชื่อทีม *<input name="teamName" required/></label>}<div className="form-grid"><label>คำนำหน้า *<input name="title" required/></label><label>ชื่อ *<input name="firstName" required/></label><label>นามสกุล *<input name="lastName" required/></label><label>หมายเลขบัตรประชาชน *<input name="citizenId" pattern="[0-9]{13}" required/></label><label>เบอร์ติดต่อ *<input name="phone" pattern="[0-9]{9,10}" required/></label><label>กองบังคับการ *<input name="division" required/></label><label>กองบัญชาการ *<input name="bureau" required/></label><label className="span-2">อีเมล *<input type="email" name="email" required/></label></div>{type==='team'&&<div className="team-members">{members.map((member,index)=><fieldset key={index}><legend>สมาชิกคนที่ {index+2}</legend><button type="button" className="remove-member" title="ลบสมาชิก" onClick={()=>setMembers(current=>current.filter((_,i)=>i!==index))}><Trash2/></button><div className="form-grid">{(['title','firstName','lastName','citizenId','phone','email','division','bureau'] as const).map(key=><label key={key}>{({title:'คำนำหน้า',firstName:'ชื่อ',lastName:'นามสกุล',citizenId:'หมายเลขบัตรประชาชน',phone:'เบอร์ติดต่อ',email:'อีเมล',division:'กองบังคับการ',bureau:'กองบัญชาการ'} as const)[key]} *<input type={key==='email'?'email':'text'} inputMode={key==='citizenId'||key==='phone'?'numeric':undefined} pattern={key==='citizenId'?'[0-9]{13}':key==='phone'?'[0-9]{9,10}':undefined} value={member[key]} onChange={event=>updateMember(index,key,event.target.value)} required/></label>)}</div></fieldset>)}{members.length<2&&<button className="add-member" type="button" onClick={()=>setMembers(current=>[...current,emptyMember()])}><Plus/> เพิ่มสมาชิก ({members.length+1}/2 คนเพิ่มเติม)</button>}</div>}</section>
<section className="form-section"><header><span>Innovation</span><h3>2. ข้อมูลผลงานนวัตกรรม</h3></header><div className="form-grid"><label>ชื่อผลงานนวัตกรรม ภาษาไทย *<input name="titleTh" required/></label><label>ชื่อผลงานนวัตกรรม ภาษาอังกฤษ<input name="titleEn"/></label><label className="span-2">คำอธิบายย่อ ไม่เกิน 500 ตัวอักษร *<textarea name="summary" minLength={20} maxLength={500} required/></label><label className="span-2">Link Video<input type="url" name="videoUrl" placeholder="Google Drive, YouTube หรือ OneDrive"/></label></div></section>
<section className="form-section"><header><span>Documents</span><h3>3. ไฟล์แนบ</h3><small>เอกสาร PDF ไม่เกิน 10 MB ต่อไฟล์</small></header><div className="document-guide">{docs.map(([,label])=><span key={label}><FileText/>{label}</span>)}</div>{docs.map(([name,label])=><label className="file-field" key={name}>{label} *<input type="file" name={name} accept="application/pdf" required/><small>รองรับเฉพาะ PDF ขนาดไม่เกิน 10 MB</small></label>)}</section>
<section className="form-section agreements"><header><span>Agreement</span><h3>ยืนยันข้อตกลงก่อนส่งใบสมัคร</h3></header><label className="consent"><input type="checkbox" name="consentRules" value="true" required/>ยินยอมรับข้อตกลงการประกวดนวัตกรรมทุกประการ และรับรองว่าข้อมูลเป็นความจริง</label><label className="consent"><input type="checkbox" name="consentPdpa" value="true" required/>ยินยอมให้จัดเก็บและประมวลผลข้อมูลส่วนบุคคลเพื่อวัตถุประสงค์การประกวดครั้งนี้</label></section>{error&&<p className="error">{error}</p>}<button className="primary submit" disabled={busy}>{busy?'กำลังส่งข้อมูล...':'ส่งผลงานเข้าประกวด'}</button></form>}
