import { mkdir, rename, writeFile } from "fs/promises";
import { NextResponse } from "next/server";
import path from "path";
import { actorFromAdminSession, recordAuditEvent } from "../../../../../lib/audit-log";
import { requireSuperAdminRequest } from "../../../../../lib/admin-guard";
import { db } from "../../../../../lib/db";

export const runtime = "nodejs";

const maxBackupBytes = 512 * 1024 * 1024;
const maxArchiveEntries = 10000;
const storageDir = process.env.APP_STORAGE_DIR ?? path.join(process.cwd(), "storage");

type ZipEntry = { name: string; data: Buffer };

export async function POST(request: Request) {
  const session = requireSuperAdminRequest(request);
  if (!session) return redirectToAdmin(request, "database_import_failed");

  try {
    const formData = await request.formData();
    const confirmation = String(formData.get("confirmation") ?? "").trim();
    const backup = formData.get("backup");
    if (confirmation !== "IMPORT" || !backup || typeof backup !== "object" || !("arrayBuffer" in backup)) {
      throw new Error("invalid import confirmation or file");
    }

    const backupFile = backup as File;
    if (backupFile.size <= 0 || backupFile.size > maxBackupBytes) throw new Error("backup file is too large or empty");
    const archive = Buffer.from(await backupFile.arrayBuffer());
    const entries = parseStoredZip(archive);
    const databaseEntry = entries.find((entry) => entry.name === "database.sql");
    if (!databaseEntry) throw new Error("database.sql is missing");
    const sql = databaseEntry.data.toString("utf8");
    validateDatabaseDump(sql, entries);

    const statementCount = await importDatabaseSql(sql);
    const storageEntries = entries.filter((entry) => entry.name.startsWith("storage/"));
    await restoreStorageFiles(storageEntries);

    await recordAuditEvent({
      actor: actorFromAdminSession(session),
      action: "system.database_import",
      entityType: "database",
      summary: "Import Full Backup ฐานข้อมูลและไฟล์เว็บไซต์ทั้งระบบ",
      payload: { statementCount, storageFileCount: storageEntries.length, archiveBytes: archive.length },
    }, request.headers);
    return redirectToAdmin(request, "database_imported");
  } catch (error) {
    console.error("database import failed", error);
    return redirectToAdmin(request, "database_import_failed");
  }
}

function parseStoredZip(archive: Buffer) {
  const entries: ZipEntry[] = [];
  const names = new Set<string>();
  let offset = 0;
  let totalBytes = 0;

  while (offset + 4 <= archive.length) {
    const signature = archive.readUInt32LE(offset);
    if (signature === 0x02014b50 || signature === 0x06054b50) break;
    if (signature !== 0x04034b50) throw new Error("unsupported ZIP format");
    if (entries.length >= maxArchiveEntries || offset + 30 > archive.length) throw new Error("ZIP has too many entries");

    const flags = archive.readUInt16LE(offset + 6);
    const compression = archive.readUInt16LE(offset + 8);
    const compressedSize = archive.readUInt32LE(offset + 18);
    const uncompressedSize = archive.readUInt32LE(offset + 22);
    const nameLength = archive.readUInt16LE(offset + 26);
    const extraLength = archive.readUInt16LE(offset + 28);
    const nameStart = offset + 30;
    const dataStart = nameStart + nameLength + extraLength;
    const dataEnd = dataStart + compressedSize;
    if ((flags & 0x0008) !== 0 || compression !== 0 || compressedSize !== uncompressedSize || dataEnd > archive.length) {
      throw new Error("ZIP must be an uncompressed backup generated by this system");
    }

    const name = archive.subarray(nameStart, nameStart + nameLength).toString("utf8").replace(/\\/g, "/");
    if (!isSafeZipName(name) || names.has(name)) throw new Error("ZIP contains an unsafe or duplicate path");
    names.add(name);
    const data = Buffer.from(archive.subarray(dataStart, dataEnd));
    totalBytes += data.length;
    if (totalBytes > maxBackupBytes) throw new Error("ZIP content is too large");
    entries.push({ name, data });
    offset = dataEnd;
  }

  if (!entries.length) throw new Error("ZIP is empty");
  return entries;
}

function isSafeZipName(name: string) {
  if (!name || name.includes("\0") || name.startsWith("/") || name.includes(":")) return false;
  const normalized = path.posix.normalize(name);
  return normalized === name && !normalized.split("/").includes("..");
}

function validateDatabaseDump(sql: string, entries: ZipEntry[]) {
  if (!sql.includes("-- Police Innovation Contest 2026 database export")) throw new Error("unsupported database dump");
  if (!entries.some((entry) => entry.name === "backup-manifest.json")) throw new Error("backup manifest is missing");
  if (/\b(?:DROP DATABASE|DROP USER|CREATE USER|ALTER USER|GRANT|REVOKE|SET GLOBAL)\b/i.test(sql)) {
    throw new Error("database dump contains forbidden account or global statements");
  }
}

async function importDatabaseSql(sql: string) {
  const connection = await db.getConnection();
  let statementCount = 0;
  try {
    for (const statement of splitSqlStatements(sql)) {
      const normalized = stripLeadingSqlComments(statement).trim();
      if (!normalized) continue;
      if (/^(?:CREATE DATABASE|USE)\b/i.test(normalized)) continue;
      await connection.query(statement);
      statementCount += 1;
    }
    return statementCount;
  } finally {
    connection.release();
  }
}

function splitSqlStatements(sql: string) {
  const statements: string[] = [];
  let start = 0;
  let quote = "";
  let escaped = false;
  for (let index = 0; index < sql.length; index += 1) {
    const character = sql[index];
    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (character === "\\") {
        escaped = true;
      } else if (character === quote) {
        quote = "";
      }
      continue;
    }
    if (character === "'" || character === '"' || character === "`") {
      quote = character;
    } else if (character === ";") {
      statements.push(sql.slice(start, index + 1));
      start = index + 1;
    }
  }
  if (sql.slice(start).trim()) statements.push(sql.slice(start));
  return statements;
}

function stripLeadingSqlComments(value: string) {
  let result = value.trimStart();
  let previous = "";
  while (result !== previous) {
    previous = result;
    result = result
      .replace(/^--[^\n]*(?:\n|$)/, "")
      .replace(/^#[^\n]*(?:\n|$)/, "")
      .replace(/^\/\*[\s\S]*?\*\//, "")
      .trimStart();
  }
  return result;
}

async function restoreStorageFiles(entries: ZipEntry[]) {
  const root = path.resolve(storageDir);
  for (const entry of entries) {
    const relative = entry.name.slice("storage/".length);
    if (!relative || relative.endsWith("/") || relative.split("/").some((part) => part === "..")) throw new Error("unsafe storage path");
    const target = path.resolve(root, relative);
    if (target !== root && !target.startsWith(`${root}${path.sep}`)) throw new Error("storage path escaped root");
    await mkdir(path.dirname(target), { recursive: true });
    const temporary = `${target}.${process.pid}.${Date.now()}.tmp`;
    await writeFile(temporary, entry.data);
    await rename(temporary, target);
  }
}

function redirectToAdmin(request: Request, notice: "database_imported" | "database_import_failed") {
  const url = new URL("/admin", request.url);
  url.searchParams.set("notice", notice);
  return NextResponse.redirect(url, 303);
}
